# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      - run:
          name: Checkout Dependencies with Carthahge
          command: carthage bootstrap

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: >
            set -o pipefail &&
            xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK"
            -destination "$DESTINATION" -configuration Debug
            ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
          environment:
            LC_CTYPE: en_US.UTF-8
            LANG: en_US.UTF-8
            WORKSPACE: JSONAPIModel.xcworkspace
            SCHEME: JSONAPIModel-iOS
            SDK: iphonesimulator12.0
            DESTINATION: "OS=12.0,name=iPhone XS"
